In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('files/customers-1000.csv')
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,FbcCaF483aFaFAE,Diana,Monroe,Bass-Wilson,Lake Jacksonmouth,Guatemala,+1-171-715-9766x54993,(489)413-7296x32807,cassidymercado@bonilla.com,2022-01-09,http://castro.net/
996,997,979c4D58Ae9a9cc,Jerry,Morales,Pratt-King,South Dominiquemouth,Georgia,132.253.8501x097,+1-301-292-8363x80270,gavin13@logan-downs.com,2021-08-21,https://www.braun.info/
997,998,D0DcF6a4BcefCc8,Tracie,Floyd,"Holt, Wilson and Shields",East Chloeshire,Solomon Islands,1193982387,(482)926-8966,lowehailey@oconnor.org,2020-04-22,http://www.zavala-rubio.com/
998,999,90EE9CbbDa374E9,Paul,Barnes,"Brown, Oliver and Haynes",South Shane,Finland,+1-537-466-3245x3699,791-835-9075,hodgeseddie@hardin-wells.com,2021-03-12,https://stone-randolph.info/
999,1000,51732B5b2328015,Dominic,Duran,Durham LLC,East Wendy,British Indian Ocean Territory (Chagos Archipe...,+1-278-758-4331,814-860-0941x057,owarner@velasquez.info,2021-12-09,http://www.cox.com/

In [5]:
df_filtered = df[['Customer Id', 'First Name', 'Last Name', 'Email']]

df_filtered

         Customer Id First Name Last Name                          Email
0    dE014d010c7ab0c     Andrew   Goodman  marieyates@gomez-spencer.info
1    2B54172c8b65eC3      Alvin      Lane          alexandra86@mccoy.com
2    d794Dd48988d2ac      Jenna   Harding        justincurtis@pierce.org
3    3b3Aa4aCc68f3Be   Fernando      Ford            adeleon@hubbard.org
4    D60df62ad2ae41E       Kara     Woods          jesus90@roberson.info
..               ...        ...       ...                            ...
995  FbcCaF483aFaFAE      Diana    Monroe     cassidymercado@bonilla.com
996  979c4D58Ae9a9cc      Jerry   Morales        gavin13@logan-downs.com
997  D0DcF6a4BcefCc8     Tracie     Floyd         lowehailey@oconnor.org
998  90EE9CbbDa374E9       Paul    Barnes   hodgeseddie@hardin-wells.com
999  51732B5b2328015    Dominic     Duran         owarner@velasquez.info

[1000 rows x 4 columns]